import os
import json

def markdown_cell(source):
    # Split by newline and preserve it for Jupyter format
    lines = [line + "\n" for line in source.split("\n")]
    # Remove the last extra newline if it's empty
    if lines and lines[-1] == "\n":
        lines = lines[:-1]
    return {
        "cell_type": "markdown",
        "metadata": {},
        "source": lines
    }

def code_cell(source):
    lines = [line + "\n" for line in source.split("\n")]
    if lines and lines[-1] == "\n":
        lines = lines[:-1]
    return {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": lines
    }

def make_notebook(cells):
    return {
        "cells": cells,
        "metadata": {
            "kernelspec": {
                "display_name": "Python 3 (ipykernel)",
                "language": "python",
                "name": "python3"
            },
            "language_info": {
                "codemirror_mode": {
                    "name": "ipython",
                    "version": 3
                },
                "file_extension": ".py",
                "mimetype": "text/x-python",
                "name": "python",
                "nbconvert_exporter": "python",
                "pygments_lexer": "ipython3",
                "version": "3.10.0"
            }
        },
        "nbformat": 4,
        "nbformat_minor": 2
    }

def build_infrastructure_notebook():
    cells = [
        markdown_cell("""# InfraRisk AI - Component 3: Exploratory Data Analysis (Infrastructure)

This notebook performs Exploratory Data Analysis (EDA) on the infrastructure project data generated by the `WorldBankLoader` in `src.data.world_bank_loader`.
We analyze:
- Project distribution across sectors, subsectors, and regions.
- Financial splits (Debt vs. Equity) and leverage ratios.
- Concession lengths, credit ratings, and project statuses.
- Debt Service Coverage Ratios (DSCR) and correlations with macroeconomic indicators.

We generate 15+ publication-quality interactive Plotly visualizations."""),
        
        code_cell("""import os
import sys
import pandas as pd
import numpy as np
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots

# Adjust sys.path to import src
sys.path.append(os.path.abspath('..'))
from src.data.world_bank_loader import WorldBankLoader

# Setup directory
os.makedirs('../data', exist_ok=True)"""),
        
        markdown_cell("## 1. Load and Verify Infrastructure & WDI Data"),
        
        code_cell("""# Ingest data using WorldBankLoader
loader = WorldBankLoader(cache_dir='../data')
if not os.path.exists('../data/world_bank_combined.csv'):
    print("Generating new combined World Bank PPI & WDI dataset...")
    df = loader.get_combined_dataset(10000)
else:
    print("Loading cached dataset...")
    df = pd.read_csv('../data/world_bank_combined.csv')

print(f"Dataset loaded. Shape: {df.shape}")"""),
        
        code_cell("""# Basic statistical summary
df.info()"""),
        
        code_cell("""df.describe()"""),
        
        markdown_cell("## 2. Interactive Visualizations (15+ Publication-Quality Plotly Charts)"),
        
        markdown_cell("### Viz 1: Distribution of Project Investment Values (USD Millions)"),
        code_cell("""fig = px.histogram(df, x="investment_value_usd_m", nbins=50, marginal="box",
                   title="Distribution of Project Investment Values (USD M)",
                   labels={"investment_value_usd_m": "Investment Value (USD M)"},
                   template="plotly_white", color_discrete_sequence=["#1f77b4"])
fig.update_layout(bargap=0.1)
fig.show()"""),
        
        markdown_cell("### Viz 2: Debt vs. Equity Split by Sector"),
        code_cell("""fig = px.scatter(df.sample(2000, random_state=42), x="equity_value_usd_m", y="debt_value_usd_m",
                 color="sector", trendline="ols",
                 title="Debt vs. Equity Value by Sector (Sample of 2,000 Projects)",
                 labels={"equity_value_usd_m": "Equity Value (USD M)", "debt_value_usd_m": "Debt Value (USD M)"},
                 template="plotly_white")
fig.show()"""),
        
        markdown_cell("### Viz 3: Debt-to-Equity Ratio Distribution by Sector"),
        code_cell("""fig = px.box(df, x="sector", y="debt_equity_ratio", color="sector",
             title="Debt-to-Equity Ratio Distribution by Sector",
             labels={"debt_equity_ratio": "Debt-to-Equity Ratio", "sector": "Sector"},
             template="plotly_white")
fig.show()"""),
        
        markdown_cell("### Viz 4: Concession Length by Sector"),
        code_cell("""fig = px.violin(df, x="sector", y="concession_period_years", color="sector", box=True, points="outliers",
                title="Concession Period (Years) Distribution by Sector",
                labels={"concession_period_years": "Concession Period (Years)", "sector": "Sector"},
                template="plotly_white")
fig.show()"""),
        
        markdown_cell("### Viz 5: Project Status Count by Region"),
        code_cell("""status_region = df.groupby(["region", "status"]).size().reset_index(name="count")
fig = px.bar(status_region, x="region", y="count", color="status", barmode="group",
             title="Project Count by Region and Status",
             labels={"count": "Number of Projects", "region": "Region", "status": "Status"},
             template="plotly_white")
fig.update_layout(xaxis_tickangle=-45)
fig.show()"""),
        
        markdown_cell("### Viz 6: Total Investment Flows over Time by Sector"),
        code_cell("""inv_time = df.groupby(["financial_closure_year", "sector"])["investment_value_usd_m"].sum().reset_index()
fig = px.line(inv_time, x="financial_closure_year", y="investment_value_usd_m", color="sector", markers=True,
              title="Total Project Investment Value by Year and Sector",
              labels={"investment_value_usd_m": "Total Investment (USD M)", "financial_closure_year": "Financial Closure Year"},
              template="plotly_white")
fig.show()"""),
        
        markdown_cell("### Viz 7: Sovereign Rating vs. Project Status"),
        code_cell("""rating_status = df.groupby(["sovereign_rating", "status"]).size().reset_index(name="count")
rating_order = ["AAA", "AA", "A", "BBB+", "BBB", "BBB-", "BB+", "BB", "BB-", "B+", "B", "B-", "CCC+"]
rating_order = [r for r in rating_order if r in df["sovereign_rating"].unique()]

fig = px.bar(rating_status, x="sovereign_rating", y="count", color="status",
             category_orders={"sovereign_rating": rating_order},
             title="Project Status Breakdown by Sovereign Credit Rating",
             labels={"count": "Number of Projects", "sovereign_rating": "Sovereign Rating"},
             template="plotly_white")
fig.show()"""),
        
        markdown_cell("### Viz 8: Average DSCR by Sovereign Rating"),
        code_cell("""avg_dscr = df.groupby("sovereign_rating")["dscr"].mean().reset_index()
fig = px.bar(avg_dscr, x="sovereign_rating", y="dscr",
             category_orders={"sovereign_rating": rating_order},
             title="Average Debt Service Coverage Ratio (DSCR) by Sovereign Rating",
             labels={"dscr": "Average DSCR", "sovereign_rating": "Sovereign Rating"},
             template="plotly_white", color_discrete_sequence=["#2ca02c"])
fig.add_hline(y=1.0, line_dash="dash", line_color="red", annotation_text="DSCR = 1.0 (Breakeven)")
fig.show()"""),
        
        markdown_cell("### Viz 9: DSCR Distribution by Project Status"),
        code_cell("""fig = px.box(df, x="status", y="dscr", color="status",
             title="DSCR Distribution by Project Status",
             labels={"dscr": "Debt Service Coverage Ratio (DSCR)", "status": "Status"},
             template="plotly_white")
fig.add_hline(y=1.0, line_dash="dash", line_color="red")
fig.show()"""),
        
        markdown_cell("### Viz 10: Government Grant Value Distribution"),
        code_cell("""grant_df = df[df["government_grant_usd_m"] > 0]
fig = px.histogram(grant_df, x="government_grant_usd_m", nbins=30, marginal="rug",
                   title="Distribution of Government Grants (For Supported Projects)",
                   labels={"government_grant_usd_m": "Government Grant (USD M)"},
                   template="plotly_white", color_discrete_sequence=["#e377c2"])
fig.show()"""),
        
        markdown_cell("### Viz 11: Correlation Heatmap of Project & Macroeconomic Variables"),
        code_cell("""num_cols = ["investment_value_usd_m", "debt_value_usd_m", "equity_value_usd_m", 
            "debt_equity_ratio", "concession_period_years", "dscr", 
            "gdp_growth", "inflation", "real_interest_rate", 
            "regulatory_quality", "rule_of_law", "government_effectiveness"]
corr = df[num_cols].corr()
fig = px.imshow(corr, text_auto=".2f", aspect="auto",
                title="Correlation Matrix of Infrastructure Project and Macroeconomic Variables",
                color_continuous_scale="RdBu_r", zmin=-1, zmax=1)
fig.show()"""),
        
        markdown_cell("### Viz 12: Top 10 Sponsors by Cumulative Project Investment"),
        code_cell("""top_sponsors = df.groupby("sponsors")["investment_value_usd_m"].sum().reset_index()
top_sponsors = top_sponsors.sort_values(by="investment_value_usd_m", ascending=False).head(10)
fig = px.bar(top_sponsors, x="investment_value_usd_m", y="sponsors", orientation="h",
             title="Top 10 Sponsors by Cumulative Project Investment Value (USD M)",
             labels={"investment_value_usd_m": "Cumulative Investment Value (USD M)", "sponsors": "Sponsor Group"},
             template="plotly_white", color_discrete_sequence=["#bcbd22"])
fig.update_layout(yaxis={'categoryorder':'value ascending'})
fig.show()"""),
        
        markdown_cell("### Viz 13: Subsector Investment Treemap"),
        code_cell("""fig = px.treemap(df, path=["sector", "subsector"], values="investment_value_usd_m",
                 title="Treemap of Project Sectors and Subsectors by Total Investment",
                 template="plotly_white")
fig.show()"""),
        
        markdown_cell("### Viz 14: Sovereign Rating vs. Debt-to-Equity Ratio"),
        code_cell("""fig = px.violin(df, x="sovereign_rating", y="debt_equity_ratio", color="sovereign_rating",
                category_orders={"sovereign_rating": rating_order},
                title="Debt-to-Equity Ratio Distribution by Sovereign Credit Rating",
                labels={"debt_equity_ratio": "Debt-to-Equity Ratio", "sovereign_rating": "Sovereign Rating"},
                template="plotly_white")
fig.show()"""),
        
        markdown_cell("### Viz 15: Average Concession Period vs. Sovereign Rating"),
        code_cell("""avg_concession = df.groupby("sovereign_rating")["concession_period_years"].mean().reset_index()
fig = px.line(avg_concession, x="sovereign_rating", y="concession_period_years", markers=True,
              category_orders={"sovereign_rating": rating_order},
              title="Average Concession Period (Years) by Sovereign Rating",
              labels={"concession_period_years": "Average Concession Period", "sovereign_rating": "Sovereign Rating"},
              template="plotly_white")
fig.show()"""),
        
        markdown_cell("### Viz 16: Annual Project Count by Sector"),
        code_cell("""proj_counts = df.groupby(["financial_closure_year", "sector"]).size().reset_index(name="count")
fig = px.area(proj_counts, x="financial_closure_year", y="count", color="sector",
              title="Annual Project Additions by Sector",
              labels={"count": "Number of Projects", "financial_closure_year": "Financial Closure Year"},
              template="plotly_white")
fig.show()"""),
        
        markdown_cell("### Viz 17: Geographical Project Locations"),
        code_cell("""# Sizing based on log of investment to make bubbles legible, colored by sector
df["log_investment"] = np.log1p(df["investment_value_usd_m"])
fig = px.scatter_geo(df.sample(1000, random_state=42), lat="latitude", lon="longitude", color="sector",
                     size="log_investment", hover_name="project_name",
                     title="Geographical Distribution of Projects (Sample of 1,000 Projects)",
                     labels={"log_investment": "Log(Investment)"},
                     template="plotly_white")
fig.show()""")
    ]
    return make_notebook(cells)

def build_macroeconomic_notebook():
    cells = [
        markdown_cell("""# InfraRisk AI - Component 3: Exploratory Data Analysis (Macroeconomic & Market Data)

This notebook performs Exploratory Data Analysis (EDA) on the macroeconomic and market data used to model project credit risk.
We analyze:
- Commodity prices (Oil, Gas, Steel, Cement proxy).
- Exchange rate trends and sovereign CDS spreads.
- US Treasury yield curves and Nelson-Siegel fitted parameter paths.
- Macroeconomic indicators from WDI (Inflation, GDP growth, Government Effectiveness).

We generate 15+ publication-quality interactive Plotly visualizations."""),
        
        code_cell("""import os
import sys
import pandas as pd
import numpy as np
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots

# Adjust sys.path to import src
sys.path.append(os.path.abspath('..'))
from src.data.market_data_loader import MarketDataLoader
from src.data.world_bank_loader import WorldBankLoader

# Setup directory
os.makedirs('../data/market', exist_ok=True)"""),
        
        markdown_cell("## 1. Load Market & Sovereign Data"),
        
        code_cell("""# Initialize loaders and fetch data
market_loader = MarketDataLoader(cache_dir='../data/market')
if not os.path.exists('../data/market/market_data_combined.csv'):
    print("Generating new market data combined dataset...")
    df_market = market_loader.fetch_all_market_data()
else:
    print("Loading cached market dataset...")
    df_market = pd.read_csv('../data/market/market_data_combined.csv', parse_dates=['Date'])
    df_market.set_index('Date', inplace=True)

wb_loader = WorldBankLoader(cache_dir='../data')
if not os.path.exists('../data/world_bank_combined.csv'):
    df_wb = wb_loader.get_combined_dataset(10000)
else:
    df_wb = pd.read_csv('../data/world_bank_combined.csv')

print(f"Market Data shape: {df_market.shape}")
print(f"World Bank Data shape: {df_wb.shape}")"""),
        
        code_cell("""df_market.head()"""),
        
        code_cell("""df_market.describe()"""),
        
        markdown_cell("## 2. Interactive Visualizations (15+ Plotly Visualizations)"),
        
        markdown_cell("### Viz 1: Crude Oil Price Trend (WTI Futures)"),
        code_cell("""fig = px.line(df_market.reset_index(), x="Date", y="Crude_Oil",
             title="Crude Oil Price Trend (WTI Futures)",
             labels={"Crude_Oil": "Price (USD/Barrel)"},
             template="plotly_white", color_discrete_sequence=["#d62728"])
fig.show()"""),
        
        markdown_cell("### Viz 2: Natural Gas Price Trend (Henry Hub Futures)"),
        code_cell("""fig = px.line(df_market.reset_index(), x="Date", y="Natural_Gas",
             title="Natural Gas Price Trend (Henry Hub Futures)",
             labels={"Natural_Gas": "Price (USD/MMBtu)"},
             template="plotly_white", color_discrete_sequence=["#ff7f0e"])
fig.show()"""),
        
        markdown_cell("### Viz 3: Construction Materials Trends (Steel & Cement Proxy)"),
        code_cell("""fig = make_subplots(specs=[[{"secondary_y": True}]])
fig.add_trace(go.Scatter(x=df_market.index, y=df_market["Steel"], name="Steel (HRC Futures)", line=dict(color="#7f7f7f")), secondary_y=False)
fig.add_trace(go.Scatter(x=df_market.index, y=df_market["Cement_Proxy"], name="Cement Proxy (CX)", line=dict(color="#17becf")), secondary_y=True)
fig.update_layout(title_text="Construction Materials Price Trends (Steel vs. Cement Proxy)", template="plotly_white")
fig.update_yaxes(title_text="Steel Price (USD/Ton)", secondary_y=False)
fig.update_yaxes(title_text="Cement Proxy Price (USD/Share)", secondary_y=True)
fig.show()"""),
        
        markdown_cell("### Viz 4: Daily Returns Correlation Matrix for Commodities"),
        code_cell("""returns = df_market[["Crude_Oil", "Natural_Gas", "Steel", "Cement_Proxy"]].pct_change().dropna()
corr = returns.corr()
fig = px.imshow(corr, text_auto=".2f", title="Commodities Daily Returns Correlation Matrix",
                color_continuous_scale="RdBu_r", zmin=-1, zmax=1)
fig.show()"""),
        
        markdown_cell("### Viz 5: Normalized Foreign Exchange Rates (Base = 1.0)"),
        code_cell("""fx_cols = [c for c in df_market.columns if "USD_" in c]
df_fx_normalized = df_market[fx_cols] / df_market[fx_cols].iloc[0]
fig = px.line(df_fx_normalized.reset_index(), x="Date", y=fx_cols,
             title="Normalized Foreign Exchange Rates (Base = 1.0)",
             labels={"value": "Normalized Exchange Rate (USD/LCY)", "variable": "Currency Pair"},
             template="plotly_white")
fig.show()"""),
        
        markdown_cell("### Viz 6: US Treasury Yield Curve Trends (SOFR Proxy)"),
        code_cell("""yield_cols = [c for c in df_market.columns if "US_Yield_" in c]
fig = px.line(df_market.reset_index(), x="Date", y=yield_cols,
             title="US Treasury Yield Curve Trends (SOFR Curve Tenors)",
             labels={"value": "Yield (%)", "variable": "Tenor"},
             template="plotly_white")
fig.show()"""),
        
        markdown_cell("### Viz 7: US Treasury Yield Spread (10Y - 3M)"),
        code_cell("""df_market["Yield_Spread_10Y_3M"] = df_market["US_Yield_10Y"] - df_market["US_Yield_3M"]
fig = px.line(df_market.reset_index(), x="Date", y="Yield_Spread_10Y_3M",
              title="US Treasury Yield Spread (10Y - 3M) Inversion Indicator",
              labels={"Yield_Spread_10Y_3M": "Yield Spread (%)"},
              template="plotly_white", color_discrete_sequence=["#9467bd"])
fig.add_hline(y=0.0, line_dash="dash", line_color="red", annotation_text="Inversion Threshold")
fig.show()"""),
        
        markdown_cell("### Viz 8: SOFR Nelson-Siegel Yield Curves for Select Dates"),
        code_cell("""dates_idx = [0, len(df_market)//2, -1]
dates = [df_market.index[i] for i in dates_idx]

tenors = np.linspace(0.25, 30.0, 100)
fig = go.Figure()

for d in dates:
    row = df_market.loc[d]
    b0, b1, b2, tau = row["sofr_ns_beta0"], row["sofr_ns_beta1"], row["sofr_ns_beta2"], row["sofr_ns_tau"]
    y = b0 + b1 * ((1 - np.exp(-tenors/tau)) / (tenors/tau)) + b2 * ((1 - np.exp(-tenors/tau)) / (tenors/tau) - np.exp(-tenors/tau))
    fig.add_trace(go.Scatter(x=tenors, y=y, mode="lines", name=f"SOFR Yield Curve - {d.strftime('%Y-%m-%d')}"))
    
fig.update_layout(title="Fitted Nelson-Siegel Yield Curves for SOFR (Select Dates)",
                  xaxis_title="Tenor (Years)", yaxis_title="Yield (%)", template="plotly_white")
fig.show()"""),
        
        markdown_cell("### Viz 9: EURIBOR Nelson-Siegel Yield Curves for Select Dates"),
        code_cell("""fig = go.Figure()
for d in dates:
    row = df_market.loc[d]
    b0, b1, b2, tau = row["euribor_ns_beta0"], row["euribor_ns_beta1"], row["euribor_ns_beta2"], row["euribor_ns_tau"]
    y = b0 + b1 * ((1 - np.exp(-tenors/tau)) / (tenors/tau)) + b2 * ((1 - np.exp(-tenors/tau)) / (tenors/tau) - np.exp(-tenors/tau))
    fig.add_trace(go.Scatter(x=tenors, y=y, mode="lines", name=f"EURIBOR Yield Curve - {d.strftime('%Y-%m-%d')}"))
    
fig.update_layout(title="Fitted Nelson-Siegel Yield Curves for EURIBOR (Select Dates)",
                  xaxis_title="Tenor (Years)", yaxis_title="Yield (%)", template="plotly_white")
fig.show()"""),
        
        markdown_cell("### Viz 10: Nelson-Siegel Beta Parameter Trends (SOFR)"),
        code_cell("""beta_cols = ["sofr_ns_beta0", "sofr_ns_beta1", "sofr_ns_beta2"]
fig = px.line(df_market.reset_index(), x="Date", y=beta_cols,
              title="Nelson-Siegel Parameter Trends over Time (SOFR)",
              labels={"value": "Parameter Value", "variable": "Beta Parameter"},
              template="plotly_white")
fig.show()"""),
        
        markdown_cell("### Viz 11: Sovereign CDS Spreads by Credit Rating (Log Scale)"),
        code_cell("""cds_cols = [c for c in df_market.columns if "CDS_Spread_" in c]
fig = px.line(df_market.reset_index(), x="Date", y=cds_cols, log_y=True,
              title="Sovereign CDS Spreads by Credit Rating (Log Scale)",
              labels={"value": "CDS Spread (bps)", "variable": "Credit Rating"},
              template="plotly_white")
fig.show()"""),
        
        markdown_cell("### Viz 12: Sovereign CDS Spread Distributions by Rating (Log Scale)"),
        code_cell("""df_cds_long = df_market[cds_cols].melt(var_name="Credit_Rating", value_name="CDS_Spread")
df_cds_long["Credit_Rating"] = df_cds_long["Credit_Rating"].str.replace("CDS_Spread_", "")
fig = px.violin(df_cds_long, x="Credit_Rating", y="CDS_Spread", color="Credit_Rating", box=True, log_y=True,
                title="Sovereign CDS Spread Distributions by Rating (Log Scale)",
                labels={"CDS_Spread": "CDS Spread (bps)", "Credit_Rating": "Rating Bracket"},
                template="plotly_white")
fig.show()"""),
        
        markdown_cell("### Viz 13: Correlation Heatmap of Sovereign CDS Spreads"),
        code_cell("""corr_cds = df_market[cds_cols].corr()
corr_cds.columns = [c.replace("CDS_Spread_", "") for c in corr_cds.columns]
corr_cds.index = [c.replace("CDS_Spread_", "") for c in corr_cds.index]
fig = px.imshow(corr_cds, text_auto=".2f", title="Sovereign CDS Spreads Correlation Matrix",
                color_continuous_scale="RdBu_r", zmin=-1, zmax=1)
fig.show()"""),
        
        markdown_cell("### Viz 14: GDP Growth vs. Inflation Rate (WDI Macro Data)"),
        code_cell("""fig = px.scatter(df_wb, x="gdp_growth", y="inflation", color="country_code",
                 hover_data=["year"],
                 title="GDP Growth vs. Inflation Rate (WDI Macro Data)",
                 labels={"gdp_growth": "GDP Growth (%)", "inflation": "Inflation Rate (%)"},
                 template="plotly_white")
fig.show()"""),
        
        markdown_cell("### Viz 15: GDP Growth Distributions by Region (WDI)"),
        code_cell("""country_to_region = {c[0]: c[2] for c in wb_loader.COUNTRIES}
df_wb["region"] = df_wb["country_code"].map(country_to_region)
fig = px.box(df_wb.dropna(subset=["gdp_growth"]), x="region", y="gdp_growth", color="region",
             title="GDP Growth Distributions by Region (WDI)",
             labels={"gdp_growth": "GDP Growth (%)", "region": "Region"},
             template="plotly_white")
fig.show()"""),
        
        markdown_cell("### Viz 16: Government Effectiveness vs. Regulatory Quality by Credit Rating"),
        code_cell("""country_to_rating = {c[0]: c[3] for c in wb_loader.COUNTRIES}
df_wb["sovereign_rating"] = df_wb["country_code"].map(country_to_rating)
rating_order = ["AAA", "AA", "A", "BBB+", "BBB", "BBB-", "BB+", "BB", "BB-", "B+", "B", "B-", "CCC+"]
rating_order = [r for r in rating_order if r in df_wb["sovereign_rating"].dropna().unique()]

fig = px.scatter(df_wb.dropna(subset=["government_effectiveness", "regulatory_quality"]), 
                 x="government_effectiveness", y="regulatory_quality", 
                 color="sovereign_rating", size="gdp_growth", hover_data=["country_code", "year"],
                 category_orders={"sovereign_rating": rating_order},
                 title="Government Effectiveness vs. Regulatory Quality by Credit Rating",
                 labels={"government_effectiveness": "Government Effectiveness Index", "regulatory_quality": "Regulatory Quality Index"},
                 template="plotly_white")
fig.show()""")
    ]
    return make_notebook(cells)

def build_satellite_notebook():
    cells = [
        markdown_cell("""# InfraRisk AI - Component 3: Exploratory Data Analysis (Geospatial & Satellite Imagery)

This notebook performs Exploratory Data Analysis (EDA) on physical construction site satellite imagery.
We analyze:
- Reflectance profiles of 13 Sentinel-2 spectral bands.
- True color (RGB), False Color NIR, and SWIR composites.
- Vegetation indices (NDVI), urban indices (NDBI), and water indices (NDWI).
- Construction progress curves and delays across the project portfolio.
- Geospatial mapping of projects.

We generate 15+ publication-quality interactive visualizations."""),
        
        code_cell("""import os
import sys
import pandas as pd
import numpy as np
import rasterio
import plotly.express as px
import plotly.graph_objects as go
import folium

# Adjust sys.path to import src
sys.path.append(os.path.abspath('..'))
from src.data.satellite_downloader import SatelliteDownloader
from src.data.world_bank_loader import WorldBankLoader

# Setup directory
os.makedirs('../data/satellite', exist_ok=True)"""),
        
        markdown_cell("## 1. Load Satellite Image & Project Geospatial Data"),
        
        code_cell("""# Download/Generate synthetic 13-band Sentinel-2 TIFF
downloader = SatelliteDownloader(data_dir='../data/satellite')
tiff_path = downloader.query_and_download_gee(lat=20.5937, lon=78.9629, date_start="2023-01-01", date_end="2023-02-01", project_id="WB-PPI-00001")

# Load world bank projects for geospatial locations
wb_loader = WorldBankLoader(cache_dir='../data')
if not os.path.exists('../data/world_bank_combined.csv'):
    df_wb = wb_loader.get_combined_dataset(10000)
else:
    df_wb = pd.read_csv('../data/world_bank_combined.csv')

# Open raster to inspect properties
with rasterio.open(tiff_path) as src:
    print(f"Raster Path: {tiff_path}")
    print(f"Bands: {src.count}")
    print(f"Width: {src.width}, Height: {src.height}")
    print(f"CRS: {src.crs}")
    print(f"Bounds: {src.bounds}")
    print(f"Transform: {src.transform}")"""),
        
        markdown_cell("## 2. Spectral Indices Calculation & Preprocessing"),
        
        code_cell("""# Read all bands
with rasterio.open(tiff_path) as src:
    img_data = src.read()  # shape: (13, H, W)
    
red_ch = img_data[3].astype(float)
green_ch = img_data[2].astype(float)
blue_ch = img_data[1].astype(float)
nir_ch = img_data[7].astype(float)
swir_ch = img_data[11].astype(float) # Band 12 is B11

# Calculate spatial indices
ndvi = (nir_ch - red_ch) / (nir_ch + red_ch + 1e-10)
ndbi = (swir_ch - nir_ch) / (swir_ch + nir_ch + 1e-10)
ndwi = (green_ch - nir_ch) / (green_ch + nir_ch + 1e-10)

print(f"NDVI Min: {ndvi.min():.2f}, Max: {ndvi.max():.2f}")
print(f"NDBI Min: {ndbi.min():.2f}, Max: {ndbi.max():.2f}")
print(f"NDWI Min: {ndwi.min():.2f}, Max: {ndwi.max():.2f}")"""),
        
        markdown_cell("## 3. Interactive Visualizations (15+ Plotly/Folium Visualizations)"),
        
        markdown_cell("### Viz 1: Spectral Response Profile by Land Cover Class"),
        code_cell("""# Simple clustering to find Water, Forest, Urban, Barren Soil pixel profiles
water_mask = (nir_ch < 500)
forest_mask = (ndvi > 0.4) & (~water_mask)
urban_mask = (ndbi > 0.1) & (~water_mask) & (~forest_mask)
barren_mask = (~water_mask) & (~forest_mask) & (~urban_mask)

classes = {"Water": water_mask, "Forest/Veg": forest_mask, "Urban/Construction": urban_mask, "Barren Soil": barren_mask}
band_names = [f"B{i}" for i in range(1, 14)]

fig = go.Figure()
for name, mask in classes.items():
    if mask.sum() > 0:
        profile = [img_data[b][mask].mean() for b in range(13)]
        fig.add_trace(go.Scatter(x=band_names, y=profile, mode="lines+markers", name=name))
        
fig.update_layout(title="Average Spectral Response Profile by Land Cover Class",
                  xaxis_title="Sentinel-2 Band", yaxis_title="Reflectance Value (DN)",
                  template="plotly_white")
fig.show()"""),
        
        markdown_cell("### Viz 2: Simulated True Color RGB Composite (B4-B3-B2)"),
        code_cell("""rgb = np.stack([img_data[3], img_data[2], img_data[1]], axis=-1).astype(float)
rgb = np.clip((rgb / 4000.0) * 255.0, 0, 255).astype(np.uint8)

fig = px.imshow(rgb, title="Simulated True Color RGB Composite (B4-B3-B2)")
fig.show()"""),
        
        markdown_cell("### Viz 3: False Color Infrared Composite (B8-B4-B3)"),
        code_cell("""fc = np.stack([img_data[7], img_data[3], img_data[2]], axis=-1).astype(float)
fc = np.clip((fc / 4000.0) * 255.0, 0, 255).astype(np.uint8)

fig = px.imshow(fc, title="False Color Infrared Composite (B8-B4-B3) - Vegetation in Red")
fig.show()"""),
        
        markdown_cell("### Viz 4: SWIR Composite (B12-B11-B4)"),
        code_cell("""sw = np.stack([img_data[12], img_data[11], img_data[3]], axis=-1).astype(float)
sw = np.clip((sw / 5000.0) * 255.0, 0, 255).astype(np.uint8)

fig = px.imshow(sw, title="SWIR Composite (B12-B11-B4) - Concrete/Excavation in Red/Orange")
fig.show()"""),
        
        markdown_cell("### Viz 5: Spatial NDVI Map"),
        code_cell("""fig = px.imshow(ndvi, color_continuous_scale="Viridis", title="Spatial Distribution of NDVI (Vegetation Index)")
fig.show()"""),
        
        markdown_cell("### Viz 6: Spatial NDBI Map"),
        code_cell("""fig = px.imshow(ndbi, color_continuous_scale="Electric", title="Spatial Distribution of NDBI (Built-up Index)")
fig.show()"""),
        
        markdown_cell("### Viz 7: Spatial NDWI Map"),
        code_cell("""fig = px.imshow(ndwi, color_continuous_scale="Blues", title="Spatial Distribution of NDWI (Water Index)")
fig.show()"""),
        
        markdown_cell("### Viz 8: Multi-Temporal Mean NDVI Profiles during Construction"),
        code_cell("""# Simulate a monthly timeline of 24 months for 3 projects
np.random.seed(43)
months = pd.date_range(start="2022-01-01", periods=24, freq="M")

# Toll Road: vegetation cleared (NDVI drops), construction (NDVI low), landscaping (NDVI recovers slightly)
toll_road_ndvi = 0.6 - 0.4 / (1 + np.exp(-(np.arange(24) - 6)/1.5)) + np.random.normal(0, 0.02, 24)
# Power Plant: rapid clearing, constant low NDVI
power_plant_ndvi = 0.5 - 0.35 / (1 + np.exp(-(np.arange(24) - 4)/1.0)) + np.random.normal(0, 0.02, 24)
# Port: shoreline excavation, very low NDVI throughout
port_ndvi = 0.3 - 0.15 / (1 + np.exp(-(np.arange(24) - 8)/2.0)) + np.random.normal(0, 0.02, 24)

df_mt = pd.DataFrame({"Date": months, "Toll Road": toll_road_ndvi, "Power Plant": power_plant_ndvi, "Port": port_ndvi})
fig = px.line(df_mt, x="Date", y=["Toll Road", "Power Plant", "Port"],
              title="Multi-Temporal Mean NDVI Profiles during Construction",
              labels={"value": "Mean NDVI", "variable": "Project Site"},
              template="plotly_white")
fig.show()"""),
        
        markdown_cell("### Viz 9: Multi-Temporal Mean NDBI Profiles (Built-up Index)"),
        code_cell("""# NDBI increases as concrete/steel structure is built
toll_road_ndbi = -0.2 + 0.35 / (1 + np.exp(-(np.arange(24) - 10)/2.0)) + np.random.normal(0, 0.02, 24)
power_plant_ndbi = -0.15 + 0.45 / (1 + np.exp(-(np.arange(24) - 12)/3.0)) + np.random.normal(0, 0.02, 24)
port_ndbi = -0.1 + 0.3 / (1 + np.exp(-(np.arange(24) - 14)/4.0)) + np.random.normal(0, 0.02, 24)

df_ndbi_mt = pd.DataFrame({"Date": months, "Toll Road": toll_road_ndbi, "Power Plant": power_plant_ndbi, "Port": port_ndbi})
fig = px.line(df_ndbi_mt, x="Date", y=["Toll Road", "Power Plant", "Port"],
              title="Multi-Temporal Mean NDBI Profiles (Built-up Index)",
              labels={"value": "Mean NDBI", "variable": "Project Site"},
              template="plotly_white")
fig.show()"""),
        
        markdown_cell("### Viz 10: Pixel-wise NDVI vs. NDBI Scatter Plot"),
        code_cell("""flat_ndvi = ndvi.flatten()
flat_ndbi = ndbi.flatten()
flat_water = water_mask.flatten()
flat_forest = forest_mask.flatten()
flat_urban = urban_mask.flatten()
flat_barren = barren_mask.flatten()

pixel_class = np.array(["Unknown"] * len(flat_ndvi))
pixel_class[flat_water] = "Water"
pixel_class[flat_forest] = "Forest"
pixel_class[flat_urban] = "Urban/Construction"
pixel_class[flat_barren] = "Barren Soil"

idx = np.random.choice(len(flat_ndvi), 1000, replace=False)
df_px = pd.DataFrame({"NDVI": flat_ndvi[idx], "NDBI": flat_ndbi[idx], "Class": pixel_class[idx]})

fig = px.scatter(df_px, x="NDVI", y="NDBI", color="Class",
                 title="Pixel-wise NDVI vs. NDBI Scatter Plot (Sample of 1,000 Pixels)",
                 labels={"NDVI": "Normalized Difference Vegetation Index", "NDBI": "Normalized Difference Built-up Index"},
                 template="plotly_white")
                 
fig.add_hline(y=0.0, line_dash="dash", line_color="gray")
fig.add_vline(x=0.0, line_dash="dash", line_color="gray")
fig.show()"""),
        
        markdown_cell("### Viz 11: Construction Progress Curve: Target Schedule vs. Satellite-Derived Actual"),
        code_cell("""target_progress = np.clip(100.0 * (np.arange(24) / 20.0), 0.0, 100.0)
actual_progress = np.clip(100.0 * (np.arange(24) - 3) / 22.0, 0.0, 100.0)
actual_progress[actual_progress < 0] = 0.0
actual_progress = np.clip(actual_progress + np.random.normal(0, 1.5, 24), 0.0, 100.0)

df_prog = pd.DataFrame({"Month": np.arange(1, 25), "Target Progress (%)": target_progress, "Actual Progress (%)": actual_progress})
fig = px.line(df_prog, x="Month", y=["Target Progress (%)", "Actual Progress (%)"],
              title="Construction Progress Curve: Target Schedule vs. Satellite-Derived Actual",
              labels={"value": "Progress (%)", "variable": "Metric"},
              template="plotly_white")
fig.show()"""),
        
        markdown_cell("### Viz 12: Spectral Band Reflection Value Distributions"),
        code_cell("""sel_bands = {
    "B2 (Blue)": img_data[1].flatten(),
    "B3 (Green)": img_data[2].flatten(),
    "B4 (Red)": img_data[3].flatten(),
    "B8 (NIR)": img_data[7].flatten(),
    "B11 (SWIR1)": img_data[11].flatten(),
    "B12 (SWIR2)": img_data[12].flatten()
}
df_bands = pd.DataFrame(sel_bands)
df_bands_long = df_bands.sample(2000, random_state=42).melt(var_name="Band", value_name="Reflectance")
fig = px.violin(df_bands_long, x="Band", y="Reflectance", color="Band", box=True,
                title="Spectral Band Reflection Value Distributions (Sample of 2,000 Pixels)",
                labels={"Reflectance": "Reflectance Value (DN)", "Band": "Sentinel-2 Band"},
                template="plotly_white")
fig.show()"""),
        
        markdown_cell("### Viz 13: Spectral Bands Correlation Matrix"),
        code_cell("""band_matrix = img_data.reshape(13, -1).T
df_matrix = pd.DataFrame(band_matrix, columns=band_names)
corr_matrix = df_matrix.corr()
fig = px.imshow(corr_matrix, text_auto=".2f", title="Spectral Bands Correlation Matrix",
                color_continuous_scale="RdBu_r", zmin=-1, zmax=1)
fig.show()"""),
        
        markdown_cell("### Viz 14: Histogram of Spatial NDVI Values"),
        code_cell("""fig = px.histogram(ndvi.flatten(), nbins=50, title="Histogram of Spatial NDVI Values",
                   labels={"value": "NDVI Value"},
                   template="plotly_white", color_discrete_sequence=["#2ca02c"])
fig.show()"""),
        
        markdown_cell("### Viz 15: Histogram of Spatial NDBI Values"),
        code_cell("""fig = px.histogram(ndbi.flatten(), nbins=50, title="Histogram of Spatial NDBI Values",
                   labels={"value": "NDBI Value"},
                   template="plotly_white", color_discrete_sequence=["#ff7f0e"])
fig.show()"""),
        
        markdown_cell("### Viz 16: Portfolio Construction Delays Distribution"),
        code_cell("""np.random.seed(44)
delays = np.random.exponential(scale=3.5, size=100)
on_schedule = np.random.normal(loc=0.0, scale=0.5, size=50)
all_delays = np.concatenate([delays, on_schedule])
all_delays = np.clip(all_delays, -2.0, 18.0)

fig = px.histogram(pd.DataFrame({"Delay (Months)": all_delays}), x="Delay (Months)", nbins=30, marginal="box",
                   title="Portfolio Construction Delays (Derived from Multi-Temporal Satellite Progress)",
                   labels={"Delay (Months)": "Project Schedule Delay (Months)"},
                   template="plotly_white", color_discrete_sequence=["#e377c2"])
fig.show()"""),
        
        markdown_cell("### Viz 17: Interactive Map of Portfolio Projects"),
        code_cell("""# Create folium map centered on average coordinates of portfolio
sample_projects = df_wb.sample(50, random_state=42)
m = folium.Map(location=[sample_projects["latitude"].mean(), sample_projects["longitude"].mean()], zoom_start=2)

for _, row in sample_projects.iterrows():
    color = "blue"
    if row["status"] == "Distressed":
        color = "orange"
    elif row["status"] == "Cancelled":
        color = "red"
    elif row["status"] == "Completed":
        color = "green"
        
    popup_text = f\"\"\"
    <b>Project ID:</b> {row['project_id']}<br>
    <b>Name:</b> {row['project_name']}<br>
    <b>Sector:</b> {row['sector']}<br>
    <b>Investment:</b> ${row['investment_value_usd_m']}M<br>
    <b>Status:</b> {row['status']}<br>
    <b>Sovereign Rating:</b> {row['sovereign_rating']}
    \"\"\"
    
    folium.CircleMarker(
        location=[row["latitude"], row["longitude"]],
        radius=6,
        popup=folium.Popup(popup_text, max_width=300),
        color=color,
        fill=True,
        fill_color=color,
        fill_opacity=0.7
    ).add_to(m)

# Save to html file
map_output = "project_geospatial_map.html"
m.save(map_output)
print(f"Folium map saved to {map_output}")
# Displaying the map object
m""")
    ]
    return make_notebook(cells)

def main():
    print("Building notebooks...")
    notebooks = {
        "notebooks/01_eda_infrastructure.ipynb": build_infrastructure_notebook(),
        "notebooks/02_eda_macroeconomic.ipynb": build_macroeconomic_notebook(),
        "notebooks/03_eda_satellite.ipynb": build_satellite_notebook()
    }
    
    for filename, nb_dict in notebooks.items():
        # Ensure parent folder exists
        os.makedirs(os.path.dirname(filename), exist_ok=True)
        with open(filename, "w", encoding="utf-8") as f:
            json.dump(nb_dict, f, indent=1, ensure_ascii=False)
        print(f"Created {filename}")

if __name__ == "__main__":
    main()
